# Generated by Django 3.2.25 on 2024-04-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0007_alter_accesstoken_user'),
        ('oauth2_provider', '0010_application_allowed_origins'),
    ]

    operations = [
    ]
